server:
  port: 8085

spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/online-shop-again
    username: onlineshop
    password: Harc3aparc3a!
    driver-class-name: com.mysql.cj.jdbc.Driver